apiVersion: v1
kind: Secret

metadata:
  name: predictive-secrets
  namespace: predictive-maintenance

type: Opaque

stringData:
  MQTT_USERNAME: "predictive-maintenance"
  MQTT_PASSWORD: "Bharath 123@#"