apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: predictive-ingress
  namespace: predictive-maintenance

spec:
  ingressClassName: nginx

  rules:
    - host: predictive.local
      http:
        paths:

          # Prometheus metrics
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: predictive-backend-service
                port:
                  number: 8000

          # FastAPI endpoints
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: predictive-backend-service
                port:
                  number: 8000

          # React frontend (keep this LAST)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: predictive-frontend-service
                port:
                  number: 80