version: "3.9"

services:

  predictive-api:

    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile

    image: advanced-predictive-maintenance-predictive-api:latest

    container_name: predictive-api

    ports:
      - "8000:8000"

    restart: unless-stopped

    volumes:
      - ./logs:/app/logs

    environment:
      - PYTHONUNBUFFERED=1
